### ISSUE TITLE
Extension is not enabled after loading

### ISSUE THREAD

**Issue by CodeCharm** [spences10/vscode-vba#1]
## Environment:
- Using VSCode 1.9.1 on Windows 7 SP1 x64 as a standard user
- Running VSCode from the %LocalAppData%\Code folder
- The VBA extension is successfully installed and appears in the Extensions pane.

## Problem:
I can see that the extension is dimmed (disabled), and the Reload button is visible.

## Steps taken to resolve (unsuccessfully)
1. Clicking Reload does reload the VSCode window, but does not alter the state of the extension: it remains disabled and the Reload button is still visible. Closing VSCode and restarting it also does not alter the state.
1. I have examined the Console output in the Developer Tools pane, and no information there seems to suggest any issues with the extension being loaded.

## Other possibly relevant info
These are all the other extensions I have installed. All except VBA are enabled and seem to function as expected:
- beautify, 0.8.8
- bootstrap-3-snippets, 0.0.9
- code-settings-sync, 2.5.0
- csharp, 1.7.0
- debugger-for-chrome, 2.5.3
- html-css-class-completion, 1.0.3
- html-snippets, 0.1.0
- JavaScriptSnippets, 1.4.0
- Material-theme, 1.0.3
- PowerShell, 0.9.0
- regex, 0.0.7
- tslint, 0.8.1
- unique-lines, 1.0.0
- vba, 1.0.13
- vba-snippets, 1.0.1
- vscode-color, 0.2.3
- vscode-eslint, 1.2.6
- vscode-icons, 7.2.0
- vscode-instant-markdown, 1.0.0
- vscode-vba-icons, 1.0.2
- xml, 1.7.0

**Comment by spences10** [comment]
Thanks a lot for filing this issue!

I have had a look and it appears that the extension does what it is meant to do, here's me testing the functionality

![vs-code-vba](https://cloud.githubusercontent.com/assets/234708/23292621/095d97ca-fa59-11e6-9188-8add39060ec6.gif)

What I will do is publish again on the Marketplace and see if that fixes it

**Comment by spences10** [comment]
Ok, pushing  patch clearly didn't work!!

I'm going to have to take a closer look, I don't have the time right now @CodeCharm [Alan?] 

The functionality is there it's just some weird bug

**Comment by spences10** [comment]
@CodeCharm just to update you on this, I'm still not clear on what is causing the extension to appear as disabled.

Is it causing you problems?

**Comment by spences10** [comment]
I see similar behaviour with `.editorconfig` as well

Leave this open but will close as a wont fix next time I review my open issues

**Comment by CodeCharm** [comment]
Hey @spences10 [Scott] (Yes, I'm Alan),

I've been keeping an eye on this. For the past few cycles, it's not been an issue for me. The extension has been staying lit up. Whatever you did (or didn't) -- it worked! I'll close this.

**Comment by spences10** [comment]
Brill, thanks Alan 👍
