### ISSUE TITLE
support for params completion

### ISSUE THREAD

**Issue by xbstory** [spences10/vscode-vba#12]
for example, Selection.xxx.

**Comment by spences10** [comment]
Hey @xhlove, thank you so much for your contribution 👍

This extension is being maintained, there's no active development going on.

I'll happily accept PRs, see #9 #10 #13 

Maybe someone from the community will oblige, until then this will remain open 🙏

Thanks again

**Comment by spences10** [comment]
See [Excel Live Server] for params completion, closing this now, thanks 🙏

[Excel Live Server]: https://marketplace.visualstudio.com/items?itemName=local-smart.excel-live-server
