### ISSUE TITLE
Have a question about suffix?

### ISSUE THREAD

**Issue by jun-jing** [spences10/vscode-vba#22]
I have pasted the VBA code into vscode editor, 
and I have installed the VScode VBA, I am just curious, what suffix should I name it? and then it can show highlight.

**Comment by spences10** [comment]
Hey @berxtjkl the file types are detailed here:

https://github.com/spences10/vscode-vba/blob/7f46f0ba1148731b29ef66bb0bd19f6f3f0128e7/syntaxes/vba.json#L4

Thanks
