### ISSUE TITLE
Keyword highlighting is missing a number of tokens

### ISSUE THREAD

**Issue by retailcoder** [spences10/vscode-vba#8]
The list of keyword tokens seems incomplete. The full list can be found here:

https://github.com/rubberduck-vba/RubberduckWeb/blob/master/RubberduckWeb/RubberduckWeb/VBA/FormattedCodeBlockBuilder.cs#L121-L290

(note, operators get keyword highlighting there)

**Comment by spences10** [comment]
closed with #9
